--권한 테이블
CREATE TABLE AUTHORITY_CODE(
    AUTH_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    AUTH_CODE VARCHAR(50) NOT NULL,
    AUTH_NAME VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(255),
    USE_YN CHAR(1) NOT NULL DEFAULT 'Y',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    UNIQUE (AUTH_CODE)
);

--권한 추가
INSERT INTO AUTHORITY_CODE
(AUTH_CODE, AUTH_NAME, DESCRIPTION)
VALUES
('MANAGER', '재고관리자', '재고 및 사용자 관리'),
('STAFF', '일반직원', '입출고 및 조회');

--사용자 테이블
CREATE TABLE USERS (
    USER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    AUTH_ID BIGINT NOT NULL,
    EMPLOYEE_ID VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    DEPARTMENT VARCHAR(100),
    NAME VARCHAR(50) NOT NULL,
    BIRTH DATE,
    PHONE VARCHAR(30),
    EMAIL VARCHAR(100),
    ADDRESS VARCHAR(255),
    HIRE_DATE DATE,
    RETIRE_DATE DATE,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'WORKING',
    USE_YN CHAR(1) NOT NULL DEFAULT 'Y',
    REMARK VARCHAR(255),
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    UNIQUE (EMPLOYEE_ID),
    UNIQUE (EMAIL),

    CONSTRAINT FK_USERS_AUTH FOREIGN KEY (AUTH_ID) REFERENCES AUTHORITY_CODE(AUTH_ID)
);

--거래처 테이블
CREATE TABLE CUSTOMERS (
    CUSTOMER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_CODE VARCHAR(50) NOT NULL,
    CUSTOMER_NAME VARCHAR(100) NOT NULL,
    CUSTOMER_TYPE VARCHAR(20) NOT NULL,
    BUSINESS_NO VARCHAR(30),
    CEO_NAME VARCHAR(50),
    PHONE VARCHAR(30),
    EMAIL VARCHAR(100),
    ADDRESS VARCHAR(255),
    MANAGER_NAME VARCHAR(50),
    MANAGER_PHONE VARCHAR(30),
    USE_YN CHAR(1) NOT NULL DEFAULT 'Y',
    REMARK VARCHAR(255),
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    UNIQUE (CUSTOMER_CODE)
);

--창고 테이블
CREATE TABLE WAREHOUSES (
    WAREHOUSE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    WAREHOUSE_CODE VARCHAR(50) NOT NULL,
    WAREHOUSE_NAME VARCHAR(100) NOT NULL,
    LOCATION VARCHAR(255),
    USE_YN CHAR(1) NOT NULL DEFAULT 'Y',
    REMARK VARCHAR(255),
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    UNIQUE (WAREHOUSE_CODE)
);

--품목 테이블
CREATE TABLE ITEMS (
    ITEM_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ITEM_CODE VARCHAR(50) NOT NULL,
    ITEM_NAME VARCHAR(100) NOT NULL,
    ITEM_TYPE VARCHAR(20) NOT NULL,
    CATEGORY VARCHAR(100),
    SPEC VARCHAR(100),
    UNIT VARCHAR(20) NOT NULL DEFAULT 'EA',
    PURCHASE_PRICE DECIMAL(15,2) DEFAULT 0.00,
    SALE_PRICE DECIMAL(15,2) DEFAULT 0.00,
    USE_YN CHAR(1) NOT NULL DEFAULT 'Y',
    REMARK VARCHAR(255),
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    UNIQUE (ITEM_CODE)
);

--현재고 테이블
CREATE TABLE STOCKS (
    STOCK_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ITEM_ID BIGINT NOT NULL,
    WAREHOUSE_ID BIGINT NOT NULL,
    QUANTITY INT NOT NULL DEFAULT 0,
    SAFETY_STOCK INT NOT NULL DEFAULT 0,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    UNIQUE (ITEM_ID, WAREHOUSE_ID),

    CONSTRAINT FK_STOCKS_ITEM FOREIGN KEY (ITEM_ID) REFERENCES ITEMS (ITEM_ID),
    CONSTRAINT FK_STOCKS_WAREHOUSE FOREIGN KEY (WAREHOUSE_ID) REFERENCES WAREHOUSES (WAREHOUSE_ID)
);

--입고 테이블
CREATE TABLE INBOUNDS (
    INBOUND_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    INBOUND_NO VARCHAR(30) NOT NULL,
    INBOUND_TYPE VARCHAR(20) NOT NULL DEFAULT 'PURCHASE',
    CUSTOMER_ID BIGINT NULL,
    WAREHOUSE_ID BIGINT NOT NULL,
    INBOUND_DATE DATE NOT NULL,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'DRAFT'
    CREATED_USER_ID BIGINT NOT NULL,
    REMARK VARCHAR(255) NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    UNIQUE (INBOUND_NO),

    CONSTRAINT FK_INBOUNDS_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS (CUSTOMER_ID),
    CONSTRAINT FK_INBOUNDS_WAREHOUSE FOREIGN KEY (WAREHOUSE_ID) REFERENCES WAREHOUSES (WAREHOUSE_ID),
    CONSTRAINT FK_INBOUNDS_USER FOREIGN KEY (CREATED_USER_ID) REFERENCES USERS (USER_ID)
);


--입고 상세 테이블
CREATE TABLE INBOUND_DETAILS (
    INBOUND_DETAIL_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    INBOUND_ID BIGINT NOT NULL,
    ITEM_ID BIGINT NOT NULL,
    QUANTITY INT NOT NULL DEFAULT 0,
    UNIT_PRICE DECIMAL(15,2) DEFAULT 0.00,
    TOTAL_PRICE DECIMAL(15,2) DEFAULT 0.00,
    REMARK VARCHAR(255) NULL,

    CONSTRAINT FK_INBOUND_DETAILS_INBOUND FOREIGN KEY (INBOUND_ID) REFERENCES INBOUNDS (INBOUND_ID),
    CONSTRAINT FK_INBOUND_DETAILS_ITEM FOREIGN KEY (ITEM_ID) REFERENCES ITEMS (ITEM_ID)
);

--출고 테이블
CREATE TABLE OUTBOUNDS (
    OUTBOUND_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    OUTBOUND_NO VARCHAR(30) NOT NULL,
    OUTBOUND_TYPE VARCHAR(20) NOT NULL DEFAULT 'SALE',
    CUSTOMER_ID BIGINT NULL,
    WAREHOUSE_ID BIGINT NOT NULL,
    OUTBOUND_DATE DATE NOT NULL,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'COMPLETED',
    CREATED_USER_ID BIGINT NOT NULL,
    REMARK VARCHAR(255),
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    UNIQUE (OUTBOUND_NO),

    CONSTRAINT FK_OUTBOUNDS_CUSTOMER
        FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS (CUSTOMER_ID),

    CONSTRAINT FK_OUTBOUNDS_WAREHOUSE
        FOREIGN KEY (WAREHOUSE_ID) REFERENCES WAREHOUSES (WAREHOUSE_ID),

    CONSTRAINT FK_OUTBOUNDS_USER
        FOREIGN KEY (CREATED_USER_ID) REFERENCES USERS (USER_ID)
);

--출고 상세 테이블




--재고 변동 이력 테이블
CREATE TABLE STOCK_HISTORIES (
    HISTORY_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ITEM_ID BIGINT NOT NULL,
    WAREHOUSE_ID BIGINT NOT NULL,
    HISTORY_TYPE VARCHAR(20) NOT NULL,
    INBOUND_ID BIGINT NULL,
    OUTBOUND_ID BIGINT NULL,
    BEFORE_QUANTITY INT NOT NULL DEFAULT 0,
    CHANGE_QUANTITY INT NOT NULL DEFAULT 0,
    AFTER_QUANTITY INT NOT NULL DEFAULT 0,
    PROCESS_USER_ID BIGINT NOT NULL,
    REMARK VARCHAR(255),
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT FK_HISTORY_ITEM FOREIGN KEY (ITEM_ID) REFERENCES ITEMS (ITEM_ID),
    CONSTRAINT FK_HISTORY_WAREHOUSE FOREIGN KEY (WAREHOUSE_ID) REFERENCES WAREHOUSES (WAREHOUSE_ID),
    CONSTRAINT FK_HISTORY_USER FOREIGN KEY (PROCESS_USER_ID) REFERENCES USERS (USER_ID),
    CONSTRAINT FK_HISTORY_INBOUND FOREIGN KEY (INBOUND_ID) REFERENCES INBOUNDS (INBOUND_ID)
);