--권한 테이블
CREATE TABLE AUTHORITY_CODE(
    AUTH_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    AUTH_CODE VARCHAR(50) NOT NULL,
    AUTH_NAME VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(255),
    USE_YN CHAR(1) NOT NULL DEFAULT 'Y',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    UNIQUE (AUTH_CODE)
);

--권한 추가
INSERT INTO AUTHORITY_CODE
(AUTH_CODE, AUTH_NAME, DESCRIPTION)
VALUES
('MANAGER', '재고관리자', '재고 및 사용자 관리'),
('STAFF', '일반직원', '입출고 및 조회');

--사용자 테이블
CREATE TABLE USERS (
    USER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    AUTH_ID BIGINT NOT NULL,
    EMPLOYEE_ID VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    DEPARTMENT VARCHAR(100),
    NAME VARCHAR(50) NOT NULL,
    BIRTH DATE,
    PHONE VARCHAR(30),
    EMAIL VARCHAR(100),
    ADDRESS VARCHAR(255),
    HIRE_DATE DATE,
    RETIRE_DATE DATE,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'WORKING',
    USE_YN CHAR(1) NOT NULL DEFAULT 'Y',
    REMARK VARCHAR(255),
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    UNIQUE (EMPLOYEE_ID),
    UNIQUE (EMAIL),

    CONSTRAINT FK_USERS_AUTH FOREIGN KEY (AUTH_ID) REFERENCES AUTHORITY_CODE(AUTH_ID)
);

--거래처 테이블
CREATE TABLE CUSTOMERS (
    CUSTOMER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_CODE VARCHAR(50) NOT NULL,
    CUSTOMER_NAME VARCHAR(100) NOT NULL,
    CUSTOMER_TYPE VARCHAR(20) NOT NULL,
    BUSINESS_NO VARCHAR(30),
    CEO_NAME VARCHAR(50),
    PHONE VARCHAR(30),
    EMAIL VARCHAR(100),
    ADDRESS VARCHAR(255),
    MANAGER_NAME VARCHAR(50),
    MANAGER_PHONE VARCHAR(30),
    USE_YN CHAR(1) NOT NULL DEFAULT 'Y',
    REMARK VARCHAR(255),
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    UNIQUE (CUSTOMER_CODE)
);

--창고 테이블
CREATE TABLE WAREHOUSES (
    WAREHOUSE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    WAREHOUSE_CODE VARCHAR(50) NOT NULL,
    WAREHOUSE_NAME VARCHAR(100) NOT NULL,
    LOCATION VARCHAR(255),
    USE_YN CHAR(1) NOT NULL DEFAULT 'Y',
    REMARK VARCHAR(255),
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    UNIQUE (WAREHOUSE_CODE)
);